name = "bookmark-manager"
compatibility_date = "2023-12-01"

# Pages 配置（前端部署）
[build]
command = "npm run build"
cwd = "."

# 兼容性标志
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
NODE_ENV = "production"