name = "bookmark-manager"
main = "src/worker/index.ts"
compatibility_date = "2023-12-01"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "bookmark-db"
database_id = "your-database-id"

# 环境变量
[vars]
ENVIRONMENT = "development"
JWT_SECRET = "your-jwt-secret-key-change-in-production"

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" }

# 生产环境密钥（通过wrangler secret命令设置）
# wrangler secret put JWT_SECRET
# wrangler secret put ADMIN_PASSWORD_HASH

# Pages配置（前端部署）
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# 兼容性标志
compatibility_flags = ["nodejs_compat"]